version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      net6:
        ipv6_address: fd16:279c:f6ef::10
    dns: fd16:279c:f6ef::1
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./:/var/www/html
    networks:
      net6:
        ipv6_address: fd16:279c:f6ef::20
    dns: fd16:279c:f6ef::1
networks:
  net6:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd16:279c:f6ef::/64
          gateway: fd16:279c:f6ef::1
